package edu.ignat.chernyshov.user.domain.authorities;

public enum RootUserAuthority {
    ROOT_ADMIN_CREATE_ROOT_ADMIN,
    ROOT_ADMIN_READ_ROOT_ADMIN,
    ROOT_ADMIN_DELETE_ROOT_ADMIN,
    ROOT_ADMIN_UPDATE_ROOT_ADMIN,
    ROOT_ADMIN_CREATE_ROOT_MODERATOR,
    ROOT_ADMIN_READ_ROOT_MODERATOR,
    ROOT_ADMIN_DELETE_ROOT_MODERATOR,
    ROOT_ADMIN_UPDATE_ROOT_MODERATOR,

    ROOT_MODERATOR_CREATE_SELLER,
    ROOT_MODERATOR_READ_SELLER,
    ROOT_MODERATOR_DELETE_SELLER,
    ROOT_MODERATOR_UPDATE_SELLER,
    ROOT_MODERATOR_CREATE_CUSTOMER,
    ROOT_MODERATOR_READ_CUSTOMER,
    ROOT_MODERATOR_DELETE_CUSTOMER,
    ROOT_MODERATOR_UPDATE_CUSTOMER,
    ROOT_MODERATOR_CREATE_CUSTOMER_PRODUCT,
    ROOT_MODERATOR_READ_CUSTOMER_PRODUCT,
    ROOT_MODERATOR_DELETE_CUSTOMER_PRODUCT,
    ROOT_MODERATOR_UPDATE_CUSTOMER_PRODUCT;
}
