spring:
    application:
        name: user-service
    datasource:
        url: jdbc:h2:mem:user-service
        driver-class-name: org.h2.Driver
        username: admin
        password: password
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format-sql: true
    h2:
        console:
            enabled: true
            path: /h2-console
logging:
    level:
        org:
            springframework:
                data:
                    jpa: DEBUG