spring:
    application:
        name: authentication-service
    datasource:
        url: jdbc:postgresql://localhost:5432/authentication-db
        driver-class-name: org.postgresql.Driver
        username: root
        password: password
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format-sql: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
    liquibase:
        change-log: classpath:/db/changelog/db.changelog-master.yaml
    kafka:
        bootstrap-servers: 
            - localhost:9092
        admin:
            auto-create: false
        topics:
            customer:
                create-profile: create-customer-profile-topic
                update-username: update-customer-username-topic
                update-email: update-customer-email-topic
                update-phone-number: update-customer-phone-number-topic
                delete-profile: delete-customer-profile-topic
            root:
                create-profile: create-root-profile-topic
                update-username: update-root-username-topic
                update-email: update-root-email-topic
                update-phone-number: update-root-phone-number-topic
                delete-profile: delete-root-profile-topic
            seller:
                create-profile: create-seller-profile-topic
                update-username: update-seller-username-topic
                update-email: update-seller-email-topic
                update-phone-number: update-seller-phone-number-topic
                delete-profile: delete-seller-profile-topic
logging:
    level:
        org:
            springframework:
                data:
                    jpa: DEBUG