spring:
    application:
        name: user-service
    datasource:
        # url: jdbc:h2:mem:user-service
        url: jdbc:postgresql://localhost:5432/authentication-db
        driver-class-name: org.postgresql.Driver
        username: root
        password: password
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format-sql: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
    level:
        org:
            springframework:
                data:
                    jpa: DEBUG