package com.ignat.chernyshov.auth.domain.authorities;

public enum SellerUserAuthority {
    SELLER_ADMIN_CREATE_SELLER_ADMIN,
    SELLER_ADMIN_READ_SELLER_ADMIN,
    SELLER_ADMIN_DELETE_SELLER_ADMIN,
    SELLER_ADMIN_UPDATE_SELLER_ADMIN,
    SELLER_ADMIN_CREATE_MANAGER,
    SELLER_ADMIN_READ_MANAGER,
    SELLER_ADMIN_DELETE_MANAGER,
    SELLER_ADMIN_UPDATE_MANAGER,
    
    SELLER_MANAGER_CREATE_PRODUCT,
    SELLER_MANAGER_READ_PRODUCT,
    SELLER_MANAGER_DELETE_PRODUCT,
    SELLER_MANAGER_UPDATE_PRODUCT;
}
